Make route_id in predictions_for_stop optional
ViViDboarder/py_nextbusnext pull request #1
Opened 2024-08-08 09:31 UTC by drozycki

The new NextBus/UmoIQ API supports URLs with the `route_id` segment omitted, like `api/pub/v1/agencies/sfmta-cis/stops/7999/predictions`. This is useful when multiple complementary routes use the same stop, such as the SFMTA `N` (light rail sharing traffic lane with cars and buses), `NBUS` (alternate bus service), and `NOWL` (overnight bus service). This PR extends the `predictions_for_stop` API by making the `route_id` param optional. I have tested this both with and without the parameter provided. I have also bumped the version.

I would like to integrate this functionality into the ha nextbus integration so that a single entity can optionally represent the combined predictions for all routes at a stop.

2024-08-12 21:24 UTC, ViViDboarder commented
This is an interesting change that I'd like to consider, but I just updated the method to perform the filter that you proposed in the hass/core repo. Can you rebase and add this again? Coupled with a refactor in the HASS component, the coordinator can more efficiently request predictions using this method and filtering results in HASS.

2024-08-16 02:55 UTC, drozycki commented
Your `unfiltered` change is interesting, although I would be concerned that the `route/stop/predictions` API could be fixed in the future and break any code that relies on its current behavior with `unfiltered = True`. The `route/predictions` API may be more stable (although nothing is guaranteed with an undocumented API anyways..) I rebased my changes on top of yours and made sure that the unfiltered response is always returned when route is omitted. I manually tested my changes in the python interactive interpreter, and the test suite passes as well.

2024-08-16 03:41 UTC, ViViDboarder commented
Since Home Assistant is really the only known use case, I could probably just remove it. I figured I’d try to cover bases to provide something backwards compatible, but I doubt there’s a good reason unless you don’t provide a route in the first place.

2024-08-16 03:46 UTC, ViViDboarder requested changes
Are tests green? It might be good to add a test that verifies the resulting API call and that filtering is skipped. I only have tests for this method because the others basically just return the JSON result as received.

2024-08-16 03:46 UTC, ViViDboarder commented on py_nextbus/client.py
>          if direction_id:
Should probably raise an error if there is a direction but no route, as that would seem invalid. Especially since we won’t filter results.

2024-08-19 03:35 UTC, drozycki commented
Added tests, all tests green, removed redundant `unfiltered` option

2024-08-19 22:37 UTC, ViViDboarder commented
I just manually merged this because pre-commit hooks were failing. Thanks!

2024-08-19 22:37 UTC, closed without merging